SELECT A.PRODUCT_ID, A.PRODUCT_NAME, A.PRICE * SUM(B.AMOUNT) TOTAL_SALES
FROM FOOD_PRODUCT A
INNER JOIN FOOD_ORDER B
ON A.PRODUCT_ID = B.PRODUCT_ID
WHERE B.PRODUCE_DATE LIKE "2022-05%"
GROUP BY A.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, A.PRODUCT_ID ASC;