SELECT L.TITLE, L.BOARD_ID, R.REPLY_ID, R.WRITER_ID,
    R.CONTENTS, DATE_FORMAT(R.CREATED_DATE, "%Y-%m-%d") CREATED_DATE
FROM USED_GOODS_BOARD L
    INNER JOIN USED_GOODS_REPLY R
    ON  L.BOARD_ID = R.BOARD_ID
WHERE L.CREATED_DATE LIKE "2022-10%"
ORDER BY R.CREATED_DATE, L.TITLE